### ISSUE TITLE
Nmag (nsim) not working in Docker container?

### ISSUE THREAD

**Issue by fangohr** [fangohr/virtualmicromagnetics#66]
An `nsim` executable exists, but doesn't start. Here are the steps to reproduce the problem:

```
fangohr$ docker run -ti virtualmicromagnetics/lite:release /bin/bash -l
Unable to find image 'virtualmicromagnetics/lite:release' locally
release: Pulling from virtualmicromagnetics/lite

96c6a1f3c3b0: Pull complete 
ed40d4bcb313: Pull complete 
b171f9dbc13b: Pull complete 
ccfc4df4fbba: Pull complete 
a3ed95caeb02: Pull complete 
2f258f36b47c: Pull complete 
9c5acb564a9e: Pull complete 
8f7e48768c40: Pull complete 
0ec2ee8b394f: Pull complete 
5978ce1d8563: Pull complete 
6210e9cdb4ad: Pull complete 
8f46d9969158: Pull complete 
Digest: sha256:5f8613dd4265de36770d665fd7bdced52572e651ee685817f83b8319171dce02
Status: Downloaded newer image for virtualmicromagnetics/lite:release
root@db9bd4bed8e0:/# nsim
root@db9bd4bed8e0:/# 
```

**Comment by sergiomtzlosa** [comment]
Hi,

I was building a docker image with nmag on my own using the vmware image and I faced the same problem, I could solve the issue by giving nmag:nmag permissions to nmag folder, in my case the command was:

`su - nmag
`
`
chown -R nmag:nmag nmag-core-0.2.1
`

After perform those commands I could get the normal nsim output on the docker image. 

I posted the final result here: https://hub.docker.com/r/sergiomtzlosa/ubuntu-nmag

Thanks

**Comment by fangohr** [comment]
Dear @sergiomtzlosa - that's really useful. Many thanks!
